[package]
name = "new_asteroids"
version = "0.1.0"
authors = ["vlad <vladzhukovtirko@gmail.com>"]
edition = "2018"

[dependencies]
astro_lib = {path = "lib"}
image = "0.21.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.release]
lto = true