cargo-features = ["profile-overrides"]
[build]
incremental = true
[package]
name = "new_asteroids"
version = "0.1.0"
authors = ["vlad <vladzhukovtirko@gmail.com>"]
edition = "2018"

[dependencies]
astro_lib = {path = "lib"}
image = "0.21.1"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[profile.dev]
opt-level = 0
debug = true


[profile.dev.overrides.astro_lib]
opt-level=0
debug=true

[profile.dev.overrides."*"]
opt-level = 3
# [profile.release]
# lto = true